"""Render transparent MORICE desktop-pet showcase assets.

The output is generated by the same ``PetOverlayWindow`` and procedural
renderers used by the running application.  It is intentionally useful both
as release-art evidence and as a quick visual-regression pass for every pet.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from dataclasses import dataclass
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
os.environ.setdefault("MORICE_DISABLE_SESSION", "1")
os.environ.setdefault("MORICE_PRELOAD", "0")
os.environ.setdefault("MORICE_REDUCE_MOTION", "1")
os.environ.setdefault("MORICE_START_AWAKE", "1")

from PIL import Image
from PySide6.QtCore import QPoint, QSignalBlocker, Qt
from PySide6.QtGui import QColor, QImage, QPainter
from PySide6.QtWidgets import QApplication

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from morice.desktop_pet import AssetLoader, PetOverlayWindow


@dataclass(frozen=True)
class Capture:
    filename: str
    pet_id: str
    state: str
    frame: int
    progress: float = 0.5
    feedback: bool = False


CAPTURES = (
    Capture("01-ironman-idle.png", "ironman_mark42", "idle", 0, 0.15),
    Capture("02-ironman-hover.png", "ironman_mark42", "hover", 2, 0.55),
    Capture("03-ironman-flight.png", "ironman_mark42", "patrol", 3, 0.65),
    Capture("04-ironman-repulsor.png", "ironman_mark42", "special", 4, 0.5),
    Capture("05-ironman-click-reaction.png", "ironman_mark42", "react", 1, 0.35, True),
    Capture("06-spiderman-perch.png", "spiderman", "perch", 1, 0.35),
    Capture("07-spiderman-swing.png", "spiderman", "swing", 4, 0.55),
    Capture("08-spiderman-web-action.png", "spiderman", "special", 3, 0.45),
    Capture("09-spiderman-escape.png", "spiderman", "escape", 6, 0.72),
    Capture("10-dog-patrol.png", "dog", "patrol", 3, 0.55),
    Capture("11-dog-play-tail-wag.png", "dog", "play", 4, 0.6),
    Capture("12-dog-sleep.png", "dog", "sleep", 2, 0.65),
    Capture("13-cat-patrol.png", "cat", "patrol", 3, 0.55),
    Capture("14-cat-play.png", "cat", "play", 4, 0.6),
    Capture("15-cat-sleep.png", "cat", "sleep", 2, 0.65),
    Capture("16-horse-patrol.png", "horse", "patrol", 3, 0.55),
    Capture("17-horse-play-jump.png", "horse", "play", 4, 0.5),
    Capture("18-horse-head-reaction.png", "horse", "react", 1, 0.35, True),
    Capture("19-skeleton-patrol.png", "skeleton", "patrol", 3, 0.55),
    Capture("20-skeleton-collapse.png", "skeleton", "special", 4, 0.5),
    Capture("21-skeleton-rattle.png", "skeleton", "react", 1, 0.35, True),
)

ANIMATIONS = {
    "ironman-mark42-animation.webp": ("ironman_mark42", ("idle", "hover", "patrol", "special")),
    "spiderman-animation.webp": ("spiderman", ("perch", "swing", "special", "escape")),
    "dog-animation.webp": ("dog", ("idle", "patrol", "play", "sleep")),
    "cat-animation.webp": ("cat", ("idle", "patrol", "play", "sleep")),
    "horse-animation.webp": ("horse", ("idle", "patrol", "play", "react")),
    "skeleton-animation.webp": ("skeleton", ("idle", "patrol", "special", "react")),
}


def _render_capture(
    app: QApplication,
    loader: AssetLoader,
    pet_id: str,
    state: str,
    frame: int,
    progress: float,
    *,
    feedback: bool = False,
    scale: int = 4,
) -> QImage:
    window = PetOverlayWindow(
        loader.load(pet_id),
        click_action="nothing",
        size="large",
        animation_speed="normal",
    )
    now = time.monotonic()
    duration = 4.0
    window.behavior.force(state, duration, now)
    window.behavior.state_started_at = now - duration * progress
    window.behavior.state_until = now + duration * (1.0 - progress)
    window.animation.set_state(state, now)
    fps = 5.0 if state in {"idle", "sleep", "perch"} else 9.0
    window.animation.started_at = now - (frame + 0.05) / fps
    window._phase = (frame / 8.0) * 6.283185307179586
    if feedback:
        window._feedback_until = now + 5.0
    window.ensurePolished()
    app.processEvents()

    image = QImage(window.size(), QImage.Format_ARGB32_Premultiplied)
    image.fill(QColor(0, 0, 0, 0))
    painter = QPainter(image)
    window.render(painter, QPoint())
    painter.end()
    window.close()
    window.deleteLater()
    app.processEvents()
    return image.scaled(
        image.width() * scale,
        image.height() * scale,
        Qt.IgnoreAspectRatio,
        Qt.FastTransformation,
    )


def _qimage_to_pillow(image: QImage) -> Image.Image:
    converted = image.convertToFormat(QImage.Format_RGBA8888)
    view = converted.bits()
    return Image.frombytes(
        "RGBA",
        (converted.width(), converted.height()),
        bytes(view),
        "raw",
        "RGBA",
        converted.bytesPerLine(),
    )


def _save_settings_capture(app: QApplication, destination: Path) -> None:
    # Importing the main UI is intentionally deferred so pet-only rendering
    # remains fast and lightweight.
    from morice.pyside_app import MoriceWindow

    window = MoriceWindow()
    window.resize(1320, 860)
    window.ensurePolished()
    window.sidebar.setVisible(True)
    with (
        QSignalBlocker(window.pet_enabled_check),
        QSignalBlocker(window.active_pet_select),
        QSignalBlocker(window.pet_size_select),
        QSignalBlocker(window.pet_animation_speed_select),
        QSignalBlocker(window.pet_click_action_select),
        QSignalBlocker(window.pet_event_frequency_select),
        QSignalBlocker(window.pet_fullscreen_check),
        QSignalBlocker(window.pet_interaction_check),
    ):
        window.pet_enabled_check.setChecked(True)
        window.active_pet_select.setCurrentIndex(
            max(0, window.active_pet_select.findData("ironman_mark42"))
        )
        window.pet_size_select.setCurrentIndex(
            max(0, window.pet_size_select.findData("large"))
        )
        window.pet_animation_speed_select.setCurrentIndex(
            max(0, window.pet_animation_speed_select.findData("normal"))
        )
        window.pet_click_action_select.setCurrentIndex(
            max(0, window.pet_click_action_select.findData("open_morice"))
        )
        window.pet_event_frequency_select.setCurrentIndex(
            max(0, window.pet_event_frequency_select.findData("normal"))
        )
        window.pet_fullscreen_check.setChecked(True)
        window.pet_interaction_check.setChecked(True)
    window.show()
    app.processEvents()
    pet_y = window.pet_enabled_check.mapTo(window.sidebar_content, QPoint()).y()
    window.sidebar_scroll.verticalScrollBar().setValue(max(0, pet_y - 86))
    app.processEvents()

    image = QImage(window.sidebar.size(), QImage.Format_ARGB32_Premultiplied)
    image.fill(QColor(0, 0, 0, 0))
    painter = QPainter(image)
    window.sidebar.render(painter, QPoint())
    painter.end()
    image.scaled(
        image.width() * 2,
        image.height() * 2,
        Qt.IgnoreAspectRatio,
        Qt.SmoothTransformation,
    ).save(str(destination), "PNG")
    window.close()
    window.deleteLater()
    app.processEvents()


def render(output_directory: Path) -> None:
    output_directory.mkdir(parents=True, exist_ok=True)
    animation_directory = output_directory / "animations"
    animation_directory.mkdir(parents=True, exist_ok=True)
    app = QApplication.instance() or QApplication([])
    app.setApplicationName("MORICE Showcase Renderer")
    loader = AssetLoader()

    for capture in CAPTURES:
        image = _render_capture(
            app,
            loader,
            capture.pet_id,
            capture.state,
            capture.frame,
            capture.progress,
            feedback=capture.feedback,
        )
        if not image.save(str(output_directory / capture.filename), "PNG"):
            raise RuntimeError(f"Could not save {capture.filename}")

    for filename, (pet_id, states) in ANIMATIONS.items():
        frames: list[Image.Image] = []
        for state in states:
            for frame in range(6):
                qimage = _render_capture(
                    app,
                    loader,
                    pet_id,
                    state,
                    frame,
                    frame / 5.0,
                    feedback=state == "react",
                    scale=3,
                )
                frames.append(_qimage_to_pillow(qimage))
        frames[0].save(
            animation_directory / filename,
            format="WEBP",
            save_all=True,
            append_images=frames[1:],
            duration=95,
            loop=0,
            lossless=True,
            method=4,
        )

    _save_settings_capture(app, output_directory / "22-pet-settings-panel.png")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=REPOSITORY_ROOT / "docs" / "screenshots" / "desktop-pets",
        help="Destination directory (default: docs/screenshots/desktop-pets)",
    )
    args = parser.parse_args()
    render(args.output.resolve())
    print(f"Rendered {len(CAPTURES) + 1} transparent PNG captures to {args.output}")
    print(f"Rendered {len(ANIMATIONS)} transparent WebP animations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
